// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiError = "InvalidCredentials" | "UserAlreadyExists" | "UserNotFound" | "InvoiceNotFound" | "InvalidToken" | "TokenExpired" | { "InternalError": string } | { "DatabaseError": string } | "Unauthorized";
