// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthResponse = { token_type: string, expires_in: number, };

export type RefreshRequest = { refresh_token: string, };

export type UserResponse = { id: string, email: string, first_name: string, last_name: string, };
