// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type User = { id: string, email: string, first_name: string, last_name: string, password_hash: string, created_at: string, updated_at: string, };
